### ISSUE TITLE
Upload error from Posit Cloud to GitHub

### ISSUE THREAD

**Issue by RakeshKothariNep** [ds4owd-001/md-02-assignments-RakeshKothariNep#1]
@larnsce @mianzg @sskorik01 
I cannot upload file from the Posit Cloud to GitHub. I have copied the code from Posit Cloud to GitHub file for module 2 assignment. File name is Module 2 Assignment - RakeshKothariNep

**Comment by RakeshKothariNep** [comment]
<img width="745" alt="image" src="https://github.com/ds4owd-001/md-02-assignments-RakeshKothariNep/assets/148181333/8c4cc118-6329-4bce-87d8-33066eef2f53">

**Comment by sskorik01** [comment]
Did you ever manage to commit and push (exercise 1)? Or is it just not working now?

**Comment by larnsce** [comment]
You have four commits on GitHub now, two of which are yours @RakeshKothariNep:

https://github.com/ds4owd-001/md-02-assignments-RakeshKothariNep/commits/main

I also see that you have added a new file. Note that your added file does not have a file ending. It needs to be `.qmd`. You can, but you don't have to add new files for the assignments. You could use the templates we provide.
